### ISSUE TITLE
换取授权访问令牌签名错误

### ISSUE THREAD

**Issue by suxuefeng20** [alipay/alipay-sdk-python-all#11]
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/alipay/aop/api/DefaultAlipayClient.py", line 129, in __prepare_request_params
    raise RequestException('[' + THREAD_LOCAL.uuid + ']request sign failed. ' + str(e))
alipay.aop.api.exception.Exception.RequestException: [3a15d500-6b07-11e9-be3a-acbc32d28d41]request sign failed. 47<14 at <TagSet object at 0x111e4cef0 tags 0:32:25> - - -

下面是代码：
from alipay.aop.api.AlipayClientConfig import AlipayClientConfig
from alipay.aop.api.DefaultAlipayClient import DefaultAlipayClient
from alipay.aop.api.request.AlipaySystemOauthTokenRequest import AlipaySystemOauthTokenRequest

alipay_client_config = AlipayClientConfig()
alipay_client_config.server_url = alipay_gateway
alipay_client_config.app_id = alipay_appid
alipay_client_config.app_private_key = alipay_aes
alipay_client_config.alipay_public_key = alipay_sign
client = DefaultAlipayClient(alipay_client_config=alipay_client_config)
model = AlipaySystemOauthTokenRequest()
model.grant_type = "authorization_code"
model.code = auth_code
result = client.execute(model)
 print(result)

是我调用的方式不对吗？ Python版本3.5.4

**Comment by suxuefeng20** [comment]
我调用的方式不对

**Comment by wym123** [comment]
所以正确的方式怎么搞呢？
